version: '3.9'

services:
  client:
    build:
      context: client
    ports:
      - 3000:3000
  posts:
    build:
      context: posts
    ports:
      - 4000:4000
  comments:
    build:
      context: comments
    ports:
      - 4001:4001
  event-bus:
    build:
      context: event-bus
    ports:
      - 4005:4005
  moderation:
    build:
      context: moderation
    ports:
      - 4003:4003
  query:
    build:
      context: query
    ports:
      - 4002:4002
    depends_on:
      - event-bus
